services:
  postgres:
    image: postgres:17.0
    restart: "always"
    networks:
      - productNetworkDb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product-service-db
  keycloak-db:
    image: postgres:17.0
    restart: "always"
    container_name: keycloak-db
    networks:
      - productNetworkDb
    ports:
      - "5433:5432"
    volumes:
      - ./docker/keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak-db
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    restart: "always"
    networks:
      - productNetworkDb
    command:
      - "start-dev"
    ports:
      - "9080:9080"
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    depends_on:
      - keycloak-db

volumes:
  postgres_data:

networks:
  productNetworkDb:
    driver: bridge