spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/spring-microservices
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    out-of-order: false

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0].name: Product Service
    urls[0].url: /aggregate/products-service/v3/api-docs
    urls[1].name: Order Service
    urls[1].url: /aggregate/orders-service/v3/api-docs
    urls[2].name: Inventory Service
    urls[2].url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /api-docs

service:
  products_url: /products
  products_host: http://localhost:7001
  orders_url: /orders
  orders_host: http://localhost:7002
  inventory_url: /inventory
  inventory_host: http://localhost:7003