spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework: INFO

server:
  port: 7002

inventory:
  url: http://localhost:7003