spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationsService
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific:
          avro:
            reader: true
        schema:
          registry:
            url: http://127.0.0.1:8085
  mail:
    host: smtp.gmail.com
    port: 587
    username: aponomarev583@gmail.com
    password: sixi cgrl eqan wukh

logging:
  level:
    org.springframework: INFO

server:
  port: 7004